#!/bin/bash

set -e

# Download a standalone sing-box CLI binary for the root tproxy daemon mode.
# Version must stay compatible with the sing-box option schema generated by
# SingBoxOptions.java (currently the 1.12.x series).

VERSION="1.12.19"
BASE="https://github.com/SagerNet/sing-box/releases/download/v${VERSION}/sing-box-${VERSION}"

DIR=app/executableSo
rm -rf "$DIR"
mkdir -p "$DIR/arm64-v8a"

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

curl -fLSs -o "$TMP/sing-box.tar.gz" "${BASE}-android-arm64.tar.gz"
tar -xzf "$TMP/sing-box.tar.gz" -C "$TMP"

cp "$TMP/sing-box-${VERSION}-android-arm64/sing-box" "$DIR/arm64-v8a/libboxd.so"
chmod 755 "$DIR/arm64-v8a/libboxd.so"

echo ">> installed $DIR/arm64-v8a/libboxd.so"