name: Preview Build
on:
  workflow_dispatch:
    inputs:
jobs:
  libcore:
    name: Native Build (LibCore)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive
      - name: Golang Status
        run: find buildScript libcore/*.sh | xargs cat | sha1sum > golang_status
      - name: Libcore Status
        run: git ls-files libcore | xargs cat | sha1sum > libcore_status
      - name: LibCore Cache
        id: cache
        uses: actions/cache@v5
        with:
          path: |
            app/libs/libcore.aar
          key: ${{ hashFiles('.github/workflows/*', 'golang_status', 'libcore_status') }}
      - name: Install Golang
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/setup-go@v6
        with:
          go-version: ^1.25
      - name: Native Build
        if: steps.cache.outputs.cache-hit != 'true'
        run: ./run lib core
  build:
    name: Build OSS APK
    runs-on: ubuntu-latest
    needs:
      - libcore
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive
      - name: Golang Status
        run: find buildScript libcore/*.sh | xargs cat | sha1sum > golang_status
      - name: Libcore Status
        run: git ls-files libcore | xargs cat | sha1sum > libcore_status
      - name: LibCore Cache
        uses: actions/cache@v5
        with:
          path: |
            app/libs/libcore.aar
          key: ${{ hashFiles('.github/workflows/*', 'golang_status', 'libcore_status') }}
      - name: HevTun Status
        run: |
          git submodule status hev-socks5-tunnel > hev_status
          cat buildScript/compile-hevtun.sh | sha1sum >> hev_status
      - name: HevTun Cache
        uses: actions/cache@v5
        with:
          path: |
            app/src/main/jniLibs
          key: hevtun-${{ hashFiles('.github/workflows/*', 'hev_status') }}
      - name: Gradle cache
        uses: actions/cache@v5
        with:
          path: ~/.gradle
          key: gradle-oss-${{ hashFiles('**/*.gradle.kts', 'buildSrc/**', 'release.keystore') }}-v2
      - name: Gradle Build
        env:
          BUILD_PLUGIN: none
        run: |
          echo "sdk.dir=${ANDROID_HOME}" > local.properties
          echo "ndk.dir=${ANDROID_HOME}/ndk/25.0.8775105" >> local.properties
          export LOCAL_PROPERTIES="${{ secrets.LOCAL_PROPERTIES }}"
          ./run init action gradle
          KEYSTORE_PASS="${{ secrets.KEYSTORE_PASS }}" ALIAS_NAME="${{ secrets.ALIAS_NAME }}" ALIAS_PASS="${{ secrets.ALIAS_PASS }}" ./gradlew app:assemblePreviewRelease --no-build-cache
      - name: Collect APKs
        run: |
          mkdir -p dist
          find app/build/outputs/apk -name "*.apk" -exec cp {} dist/ \;
          ls -lh dist/

      - name: Upload arm64-v8a APK
        uses: actions/upload-artifact@v7
        with:
          path: dist/*-arm64-v8a.apk
          if-no-files-found: ignore
          archive: false

      - name: Upload armeabi-v7a APK
        uses: actions/upload-artifact@v7
        with:
          path: dist/*-armeabi-v7a.apk
          if-no-files-found: ignore
          archive: false

      - name: Upload x86_64 APK
        uses: actions/upload-artifact@v7
        with:
          path: dist/*-x86_64.apk
          if-no-files-found: ignore
          archive: false

      - name: Upload x86 APK
        uses: actions/upload-artifact@v7
        with:
          path: dist/*-x86.apk
          if-no-files-found: ignore
          archive: false

      - name: Upload Universal APK
        uses: actions/upload-artifact@v7
        with:
          path: dist/*-universal.apk
          if-no-files-found: ignore
          archive: false
