name: Release Build
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release Tag"
        required: true
      publish:
        description: "Publish: If want ignore"
        required: false
jobs:
  libcore:
    name: Native Build (LibCore)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive
      - name: Golang Status
        run: find buildScript libcore/*.sh | xargs cat | sha1sum > golang_status
      - name: Libcore Status
        run: git ls-files libcore | xargs cat | sha1sum > libcore_status
      - name: LibCore Cache
        id: cache
        uses: actions/cache@v5
        with:
          path: |
            app/libs/libcore.aar
          key: ${{ hashFiles('.github/workflows/*', 'golang_status', 'libcore_status') }}
      - name: Install Golang
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/setup-go@v6
        with:
          go-version: ^1.25
      - name: Native Build
        if: steps.cache.outputs.cache-hit != 'true'
        run: ./run lib core
  build:
    name: Build OSS APK
    runs-on: ubuntu-latest
    needs:
      - libcore
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive
      - name: Golang Status
        run: find buildScript libcore/*.sh | xargs cat | sha1sum > golang_status
      - name: Libcore Status
        run: git ls-files libcore | xargs cat | sha1sum > libcore_status
      - name: LibCore Cache
        uses: actions/cache@v5
        with:
          path: |
            app/libs/libcore.aar
          key: ${{ hashFiles('.github/workflows/*', 'golang_status', 'libcore_status') }}
      - name: HevTun Status
        run: |
          git submodule status hev-socks5-tunnel > hev_status
          cat buildScript/compile-hevtun.sh | sha1sum >> hev_status
      - name: HevTun Cache
        uses: actions/cache@v5
        with:
          path: |
            app/src/main/jniLibs
          key: hevtun-${{ hashFiles('.github/workflows/*', 'hev_status') }}
      - name: Gradle cache
        uses: actions/cache@v5
        with:
          path: ~/.gradle
          key: gradle-oss-${{ hashFiles('**/*.gradle.kts', 'buildSrc/**', 'release.keystore') }}-v2
      - name: Gradle Build
        env:
          BUILD_PLUGIN: none
        run: |
          echo "sdk.dir=${ANDROID_HOME}" > local.properties
          echo "ndk.dir=${ANDROID_HOME}/ndk/25.0.8775105" >> local.properties
          export LOCAL_PROPERTIES="${{ secrets.LOCAL_PROPERTIES }}"
          ./run init action gradle
          export KEYSTORE_PASS="${{ secrets.KEYSTORE_PASS || 'nekobox123' }}"
          export ALIAS_NAME="${{ secrets.ALIAS_NAME || 'nekobox' }}"
          export ALIAS_PASS="${{ secrets.ALIAS_PASS || 'nekobox123' }}"
          ./gradlew app:assembleOssRelease --no-build-cache
      - name: Collect APKs
        run: |
          mkdir -p dist
          find app/build/outputs/apk -name "*.apk" -exec cp {} dist/ \;
          ls -lh dist/

      - name: Upload arm64-v8a APK
        uses: actions/upload-artifact@v4
        with:
          name: NekoBox-arm64-v8a
          path: dist/*arm64-v8a*.apk
          if-no-files-found: ignore

      - name: Upload armeabi-v7a APK
        uses: actions/upload-artifact@v4
        with:
          name: NekoBox-armeabi-v7a
          path: dist/*armeabi-v7a*.apk
          if-no-files-found: ignore

      - name: Upload x86_64 APK
        uses: actions/upload-artifact@v4
        with:
          name: NekoBox-x86_64
          path: dist/*x86_64*.apk
          if-no-files-found: ignore

      - name: Upload x86 APK
        uses: actions/upload-artifact@v4
        with:
          name: NekoBox-x86
          path: dist/*x86*.apk
          if-no-files-found: ignore

      - name: Upload Universal APK
        uses: actions/upload-artifact@v4
        with:
          name: NekoBox-universal
          path: dist/*universal*.apk
          if-no-files-found: ignore
  publish:
    name: Publish Release
    if: github.event.inputs.publish != 'y'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Release
        run: |
          wget -O ghr.tar.gz https://github.com/tcnksm/ghr/releases/download/v0.13.0/ghr_v0.13.0_linux_amd64.tar.gz
          tar -xvf ghr.tar.gz
          mv ghr*linux_amd64/ghr .
          mkdir apks
          find artifacts -name "*.apk" -exec cp {} apks \;
          ./ghr -delete -t "${{ github.token }}" -n "${{ github.event.inputs.tag }}" "${{ github.event.inputs.tag }}" apks
